import Navigation from "@/components/navigation";
import "./globals.css";
import { Container } from "@mui/material";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main>
          <Container sx={{ my: 3 }}>
            {children}
          </Container>
        </main>
      </body>
    </html >
  );
}
